export const ArticlesActionTypes = {
    ADD_ARTICLE: "ADD_ARTICLE",
    UPDATE_ARTICLE_FIELD: "UPDATE_ARTICLE_FIELD",
    DELETE_ARTICLE: "DELETE_ARTICLE",
    ADD_COMMENT: "ADD_COMMENT",
    FILTER_ARTICLE: "FILTER_ARTICLE"
}
